[build]
publish = "public"
command = "bun build ./bunapi/index.ts && bun run ./esmscript.prod.mjs && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.124.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
